### ISSUE TITLE
Stop Copying

### ISSUE THREAD

**Issue by sshashwats** [big-javascript-fan/MVVM-android#1]
You have copied and published our code as your repo. Remove it immediately.

**Comment by big-javascript-fan** [comment]
Hi, I am not sure that is copy your code. this is just blank repo. nothing is here and I wanna upload sometime later.
what you mean copied? really cannot understand.

**Comment by sshashwats** [comment]
https://github.com/all-Jack-of-trade/newgmcins - This is my repo and you have bluntly copied and pasted it.

**Comment by sshashwats** [comment]
Remove it right away and I know your real identity as well. You have signed an NDA with us and breached it

**Comment by big-javascript-fan** [comment]
ok, I can understand what you mean. I think .. that is nDA or not. but I will remove asap.

**Comment by sshashwats** [comment]
It was not appreciated at all. We have lost so much because of this and I don't expect you to put things which doesn't belong to you. I can still see the repo. Remove it right away
